[package]
name = "quic"
version = "0.1.0"
authors = ["Roger Qiu <roger.qiu@polyhack.io>"]
license-file = "LICENSE"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
num_cpus = "1"
quiche = "0.16.0"
ring = "0.16"
mio = { version = "0.8", features = ["net", "os-poll"] }
url = "1"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
