[package]
name = "quic"
version = "0.1.0"
authors = ["Roger Qiu <roger.qiu@polyhack.io>"]
license-file = "LICENSE"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["async"] }
napi-derive = "2"
quiche = "0.16.0"
ring = "0.16"

[build-dependencies]
napi-build = "2"
# url = "1"
# num_cpus = "1"
# mio = { version = "0.8", features = ["net", "os-poll"] }

# [dependencies.neon]
# version = "0.10"
# default-features = false
# features = ["napi-6"]
