/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function plus100(input: number): number
export interface Host {
  hostname: string
  port: number
}
export interface SendInfo {
  from: Host
  to: Host
  at: ExternalObject<Instant>
}
export interface SendReturn {
  out: Buffer
  info: SendInfo
}
export class Config {
  constructor()
  verifyPeer(verify: boolean): void
  setMaxIdleTimeout(timeout: number): void
}
export class Connection {
  constructor(config: Config)
  send(): SendReturn
}
